/* Extra interactive experiences - intentionally different in each world */
(function(){
  const $=id=>document.getElementById(id);
  const add=(stageId,label,fn)=>{const st=$(stageId);const tools=st?.parentElement?.querySelector('.tools');if(!tools||tools.querySelector('[data-extra="'+label+'"]'))return;const b=document.createElement('button');b.className='tile';b.dataset.extra=label;b.textContent=label;b.onclick=fn;tools.appendChild(b)};
  const clear=st=>{if(window.gameCleanup)window.gameCleanup();st.innerHTML=''};

  function flowerPalette(){const st=$('bayanStage');clear(st);st.innerHTML='<div class="msg show">صممي وردتك الخاصة 🌷 اختاري لون البتلات ثم اضغطي وسطها</div><div class="palette">'+['🌸','🌷','🌺','🌹','🌻'].map((x,i)=>`<button class="paletteItem" data-i="${i}">${x}</button>`).join('')+'</div><div id="canvasFlower" class="canvasFlower">🌱</div>';
    st.querySelectorAll('.paletteItem').forEach(b=>b.onclick=()=>{const f=$('canvasFlower');f.textContent=b.textContent;f.classList.add('grow');setTimeout(()=>f.classList.remove('grow'),400)});
    $('canvasFlower').onclick=()=>{rain(['🌸','🌷','🌹'],20);msg('bayanMsg','صارت الوردة من اختيارك إلك وحدك 🌷');};
  }
  function wateringChallenge(){const st=$('bayanStage');clear(st);st.innerHTML='<div class="msg show">حركي قطرة الماء فوق الوردة واسقيها 🌱</div><div class="waterTrack"><div id="drop" class="waterDrop">💧</div><div class="waterFlower">🌷</div></div><div class="gameHud" id="waterHud">0 / 5</div>';
    let n=0;const d=$('drop'), track=st.querySelector('.waterTrack');let down=false;const move=e=>{if(!down)return;const r=track.getBoundingClientRect();d.style.left=Math.max(4,Math.min(96,(e.clientX-r.left)/r.width*100))+'%';};d.onpointerdown=()=>{down=true;d.setPointerCapture?.(event.pointerId)};d.onpointerup=()=>{down=false;const x=parseFloat(d.style.left)||0;if(x>78){n++;$('waterHud').textContent=n+' / 5';d.style.left='10%';if(n>=5){msg('bayanMsg','سقيتيها لحد ما تفتحت 🌷✨');rain(['🌸','🌹'],22)}}};st.addEventListener('pointermove',move);gameCleanup=()=>st.removeEventListener('pointermove',move);
  }

  function galaxyDraw(){const st=$('byounStage');clear(st);st.innerHTML='<div class="msg show">ارسمي مسارًا بإصبعك داخل المجرة ✨</div><canvas id="galaxy" class="galaxyCanvas"></canvas><button class="clearDraw" id="clearDraw">مسح الرسم</button>';const c=$('galaxy'),ctx=c.getContext('2d');const resize=()=>{c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio)};resize();let drawing=false,last=null;c.onpointerdown=e=>{drawing=true;last=[e.offsetX,e.offsetY]};c.onpointermove=e=>{if(!drawing)return;ctx.beginPath();ctx.moveTo(last[0],last[1]);ctx.lineTo(e.offsetX,e.offsetY);ctx.strokeStyle='rgba(190,220,255,.9)';ctx.lineWidth=2;ctx.stroke();last=[e.offsetX,e.offsetY]};c.onpointerup=()=>{drawing=false;last=null};$('clearDraw').onclick=()=>ctx.clearRect(0,0,c.clientWidth,c.clientHeight);}
  function planetMatch(){const st=$('byounStage');clear(st);st.innerHTML='<div class="msg show">اختاري الكوكب الذي يكمل النظام الشمسي 🪐</div><div class="planetChoices">'+['🪐','🌍','☀️','🌙'].map(x=>`<button>${x}</button>`).join('')+'</div><div class="systemCenter">☀️</div>';st.querySelectorAll('.planetChoices button').forEach((b,i)=>b.onclick=()=>{if(i===0){msg('byounMsg','اختيار صحيح! مدار كامل حول الشمس 🪐✨');rain(['⭐','✨'],18)}else msg('byounMsg','جربي مرة ثانية... السماء مخبية الجواب 😌')});}
  function starMap(){const st=$('byounStage');clear(st);st.innerHTML='<div class="msg show">حرّكي الهاتف أو إصبعك وابحثي عن النجمة التي تلمع أكثر ⭐</div><div id="mapStars" class="mapStars"></div>';const host=$('mapStars');for(let i=0;i<14;i++){const s=document.createElement('button');s.textContent='·';s.className='mapStar';s.style.left=Math.random()*90+'%';s.style.top=Math.random()*80+'%';s.onclick=()=>{if(Math.random()>.72){s.textContent='⭐';s.classList.add('big');msg('byounMsg','لقيتي النجمة السرية 🌟');rain(['⭐'],15)}else s.textContent='✦'};host.appendChild(s)}}

  function lockBox(){const st=$('byontiStage');clear(st);st.innerHTML='<div class="msg show">الصندوق مقفول 🔐 رتبي الأرقام من الأصغر للأكبر</div><div class="lockDigits"></div><div class="lockBox">🔒</div>';const vals=[3,1,4,2].sort(()=>Math.random()-.5),host=st.querySelector('.lockDigits');vals.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.onclick=()=>{b.classList.add('chosen');if(host.querySelectorAll('.chosen').length===4){const arr=[...host.querySelectorAll('.chosen')].map(x=>+x.textContent);if(arr.join('')==='1234'){st.querySelector('.lockBox').textContent='🎁';msg('byontiMsg','انفتح الصندوق! في مفاجأة إلك 🎁💗');rain(['💗','✨'],24)}else{host.querySelectorAll('.chosen').forEach(x=>x.classList.remove('chosen'));msg('byontiMsg','الترتيب مش صحيح، جربي مرة ثانية 😌')}}};host.appendChild(b)})}
  function ribbonBuild(){const st=$('byontiStage');clear(st);st.innerHTML='<div class="msg show">ركبي سوار الذكريات: اختاري 5 خرزات بالترتيب الذي يعجبك 🎀</div><div class="beads">'+['🩷','💜','🤍','💙','💛','❤️'].map(x=>`<button>${x}</button>`).join('')+'</div><div id="bracelet" class="bracelet"></div>';let n=0;st.querySelectorAll('.beads button').forEach(b=>b.onclick=()=>{if(n>=5)return;const x=document.createElement('span');x.textContent=b.textContent;$('bracelet').appendChild(x);n++;if(n===5){msg('byontiMsg','صار عندك سوار خاص من اختيارك 🎀💗');rain(['✨','💗'],18)}})}
  function lightRoom(){const st=$('byontiStage');clear(st);st.innerHTML='<div class="msg show">المسي الشاشة لتشوفي كيف يتغير الضوء ✨</div><div class="lightRoom" id="lightRoom">💗</div>';let n=0;st.onclick=e=>{n++;st.style.setProperty('--light',Math.min(1,n/10));const r=document.createElement('span');r.className='lightDot';r.style.left=e.offsetX+'px';r.style.top=e.offsetY+'px';st.appendChild(r);if(n===10)msg('byontiMsg','كل لمسة أضافت ضوء جديد ✨❤️')}}

  window.addEventListener('load',()=>{
    setTimeout(()=>{
      add('bayanStage','🎨 صممي وردتك',flowerPalette);add('bayanStage','💧 تحدي سقي الوردة',wateringChallenge);
      add('byounStage','🖌️ ارسمي مجرتك',galaxyDraw);add('byounStage','🪐 اختبري مدارك',planetMatch);add('byounStage','🔭 خريطة النجوم',starMap);
      add('byontiStage','🔐 افتحي القفل',lockBox);add('byontiStage','🎀 اصنعي سوارك',ribbonBuild);add('byontiStage','✨ غرفة الضوء',lightRoom);
    },300);
  });
})();
