(()=>{
const A=document.getElementById('audio');
const worlds={bayan:{name:'بيان',emoji:'🌷',rain:['🌹','❤️','💗']},byoun:{name:'بيون',emoji:'🌙',rain:['⭐','🌙','💙','❤️']},byonti:{name:'بيونتي',emoji:'💗',rain:['❤️','💗','💖','💕','💘']}};
let current='',gameTimer=null;
const $=s=>document.querySelector(s);
function toast(t){let x=$('#premiumToast');if(!x){x=document.createElement('div');x.id='premiumToast';x.className='toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),2200)}
function spark(x,y){for(let i=0;i<7;i++){let s=document.createElement('span');s.className='spark';s.textContent=['✨','💗','❤️','✦'][Math.floor(Math.random()*4)];s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',(Math.random()*140-70)+'px');s.style.setProperty('--y',(Math.random()*-120-20)+'px');document.body.appendChild(s);setTimeout(()=>s.remove(),950)}}
function ambientRain(n=18){if(!current||!worlds[current])return;for(let i=0;i<n;i++){let e=document.createElement('div');e.className='rain';e.textContent=worlds[current].rain[Math.floor(Math.random()*worlds[current].rain.length)];e.style.left=Math.random()*100+'vw';e.style.fontSize=(15+Math.random()*22)+'px';e.style.animationDuration=(4+Math.random()*5)+'s';e.style.setProperty('--drift',(Math.random()*160-80)+'px');document.body.appendChild(e);setTimeout(()=>e.remove(),9500)}}
function modal(title,html){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modalBox"><div class="modalEmoji">${worlds[current]?.emoji||'❤️'}</div><h2>${title}</h2><div>${html}</div><button class="btn" data-close>رجوع</button></div>`;document.body.appendChild(m);requestAnimationFrame(()=>m.classList.add('show'));m.addEventListener('click',e=>{if(e.target===m||e.target.matches('[data-close]')){m.classList.remove('show');setTimeout(()=>m.remove(),300)}});return m}
function heartHunt(){let m=modal('صيد القلوب ❤️',`<p>عندك 10 ثواني تجمعي 7 قلوب. كل قلب بنقطة.</p><div class="score" id="huntScore">0 / 7</div><div class="timer" id="huntTime">10</div><div class="tapArena" id="huntArena"></div>`);let arena=m.querySelector('#huntArena'),score=0,time=10;const spawn=()=>{let h=document.createElement('button');h.className='tapHeart';h.textContent=worlds[current].rain[Math.floor(Math.random()*worlds[current].rain.length)];h.style.left=Math.random()*88+'%';h.style.top=Math.random()*78+'%';h.onclick=()=>{score++;h.remove();m.querySelector('#huntScore').textContent=score+' / 7';spark(Math.random()*innerWidth,Math.random()*innerHeight);if(score>=7){clearInterval(gameTimer);toast('فزتي! ❤️');}};arena.appendChild(h);setTimeout(()=>h.remove(),1200)};spawn();let sp=setInterval(spawn,900);gameTimer=setInterval(()=>{time--;m.querySelector('#huntTime').textContent=time;if(time<=0||score>=7){clearInterval(gameTimer);clearInterval(sp);if(score<7)toast('جولة حلوة! جربي مرة ثانية 💗')}},1000)}
function fortune(){let msgs={bayan:['وردة اليوم: شيء جميل يستحق الاحتفال 🌷','رسالة اليوم: خلي يومك مليان أشياء بسيطة تفرحك ❤️','مفاجأة اليوم: افتحي الموقع مرة ثانية يمكن تلاقي شيء جديد ✨'],byoun:['نجمة اليوم: اختاري حلم صغير وابدئي فيه ⭐','رسالة الليل: الهدوء أحيانًا أجمل مفاجأة 🌙','إشارة اليوم: خلي عندك وقت لشيء تحبيه 💙'],byonti:['كلمة اليوم: أجمل الأشياء هي التي تجعل اليوم أخف 💗','رسالة اليوم: ابتسامة واحدة ممكن تغيّر مزاج يوم كامل ❤️','مفاجأة اليوم: في كل مرة زر جديد ممكن يعطي نتيجة مختلفة ✨']}[current];modal('مفاجأة اليوم',`<p class="question">${msgs[Math.floor(Math.random()*msgs.length)]}</p>`)}
function addButtons(){if(!current)return;let sec=document.getElementById(current);if(!sec||sec.dataset.enhanced)return;sec.dataset.enhanced='1';let games=sec.querySelector('.games');if(!games)return;let wrap=document.createElement('div');wrap.className='premiumActions';wrap.innerHTML='<button class="premiumBtn" data-hunt>💞 صيد القلوب</button><button class="premiumBtn" data-fortune>🎁 مفاجأة عشوائية</button>';games.after(wrap);wrap.querySelector('[data-hunt]').onclick=heartHunt;wrap.querySelector('[data-fortune]').onclick=fortune;}
window.addEventListener('click',e=>{let r=document.createElement('span');r.className='rippleFx';r.style.left=e.clientX+'px';r.style.top=e.clientY+'px';document.body.appendChild(r);setTimeout(()=>r.remove(),700);if(e.target.closest('.choice,.game,.btn,.premiumBtn'))spark(e.clientX,e.clientY)});
const oldPick=window.pick;window.pick=function(name,id){oldPick?.(name,id);current=id;setTimeout(()=>{addButtons();ambientRain(12)},80)};
const oldGo=window.go;window.go=function(id){oldGo?.(id);if(id==='bayan'||id==='byoun'||id==='byonti'){current=id;setTimeout(addButtons,50)}};
setInterval(()=>{if(current&&document.getElementById(current)?.classList.contains('active'))ambientRain(3)},4200);
window.addEventListener('load',()=>{let p=document.createElement('div');p.className='progressTop';p.innerHTML='<i></i>';document.body.appendChild(p);window.addEventListener('scroll',()=>{let h=document.documentElement.scrollHeight-innerHeight;p.firstElementChild.style.width=(h>0?(scrollY/h)*100:0)+'%'},{passive:true})});
})();
