(()=>{
  const names={bayan:'بيان',byoun:'بيون',byonti:'بيونتي'};
  const world=()=>document.querySelector('.screen.active')?.id||'bayan';
  const msgBox=()=>document.getElementById(world()+'Msg');
  function scrollToResult(){const el=msgBox();if(!el||!el.textContent.trim())return;setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'}),80)}
  ['bayanMsg','byounMsg','byontiMsg'].forEach(id=>{const el=document.getElementById(id);if(el)new MutationObserver(scrollToResult).observe(el,{subtree:true,childList:true,characterData:true,attributes:true})});
  document.addEventListener('click',e=>{if(e.target.closest('.tools .tile,.choices .tile,.game,.choice,.btn'))setTimeout(scrollToResult,180)},true);

  // One copy only for dynamically-created activities.
  const originalAdd=window.addWorldTools;
  if(originalAdd){window.addWorldTools=function(stageId,items){const host=document.getElementById(stageId)?.parentElement?.querySelector('.tools');if(!host)return;const wanted=new Set(items.map(x=>x[0]));const old=[...host.querySelectorAll('.dynamicTool')];old.forEach(b=>{if(wanted.has(b.dataset.key))b.remove()});originalAdd(stageId,items);host.querySelectorAll('.tile').forEach(b=>{if(wanted.has(b.textContent.trim())){b.classList.add('dynamicTool');b.dataset.key=b.textContent.trim()}});const seen=new Set();[...host.querySelectorAll('.dynamicTool')].forEach(b=>{if(seen.has(b.dataset.key))b.remove();else seen.add(b.dataset.key)})}}

  // Bouquet: choose exactly three flowers, then rain only those chosen flowers.
  window.bouquetGame=function(){
    const st=document.getElementById('bayanStage');if(!st)return;if(typeof window.gameCleanup==='function')window.gameCleanup();
    st.innerHTML='<div class="gameHud">🌷 اختاري 3 ورود للباقة</div><div class="bouquetChoices"></div><div class="bouquetPreview" id="bouquetPreview">الباقة: فارغة</div>';
    const box=st.querySelector('.bouquetChoices'),preview=st.querySelector('#bouquetPreview');const flowers=['🌹','🌷','🌸','🌺','🌻','💐'];let selected=[];
    flowers.forEach(f=>{const b=document.createElement('button');b.type='button';b.className='bouquetFlower';b.textContent=f;b.onclick=()=>{if(selected.includes(f)){selected=selected.filter(x=>x!==f);b.classList.remove('selected')}else if(selected.length<3){selected.push(f);b.classList.add('selected')}preview.textContent=selected.length?'الباقة: '+selected.join(' '):'الباقة: فارغة';if(selected.length===3){msg('bayanMsg','هاي الباقة اللي اخترتيها إلك يا بيان 🌷❤️');rain(selected,55)}};box.appendChild(b)})
  };

  // Letter: preserve the user's intended poem lines; each line is independently fitted so words never jump to the next line.
  function prepareLetter(){const env=document.querySelector('#bayanLetter .envelope');if(!env)return;env.style.width='min(560px,94vw)';env.style.margin='18px auto 30px';const paper=env.querySelector('.paper');if(!paper)return;
    const lines=['صَبَاحُ الخَيْرِ لِوَجْهِكِ الذِي أَقْبَلَ فَأَنَارَ وَلِعَيْنَيْكِ اللَّتَيْنِ تَخْتَصِرَانِ النَّهَار','أَشْرَقَتِ الشّمْسُ فَطَابَ الوُجُودُ وَاسْتَدَار وأَقْبَلتِ فِي قَلْبِي فَتَوَهَجَ العِشْقُ وَاسْتَنَار','يَبْدَأُ عُمْرِي حِينَمَا يَلُوحُ طَيْفُكِ وَيَسْتَقِيمُ نَبْضِي إِذْ يَزُورُنِي حُسْنُكِ الفَرِيد','فَمَا الصّبَاحُ فِي عُرْفِي إِلا لَمْحَةً مِنْ خَيَالِكِ وَمَا الضِّيَاءُ فِي كَوْنِي إِلا خُطْوَةً فِي دَلَالِكِ ... صَبَاحِي أَنْتِ ❤️'];paper.textContent='';lines.forEach((line,i)=>{if(i)paper.appendChild(document.createElement('br'));const s=document.createElement('span');s.className='letterLine';s.textContent=line;paper.appendChild(s)});requestAnimationFrame(()=>fitLines(paper))}
  function fitLines(paper){const lines=[...paper.querySelectorAll('.letterLine')];const max=17;lines.forEach(s=>{s.style.fontSize=max+'px';while(s.scrollWidth>s.clientWidth&&parseFloat(s.style.fontSize)>9)s.style.fontSize=(parseFloat(s.style.fontSize)-.25)+'px'})}
  window.openEnvelope=function(){if(typeof window.gameCleanup==='function')window.gameCleanup();if(typeof window.go==='function')window.go('bayanLetter');requestAnimationFrame(()=>{prepareLetter();const env=document.querySelector('#bayanLetter .envelope');if(env)env.classList.add('open')})};
  document.addEventListener('DOMContentLoaded',prepareLetter);

  // Reliable heart hunt and popup.
  window.huntHearts=function(){const st=document.getElementById('bayanStage');if(!st)return;if(typeof window.gameCleanup==='function')window.gameCleanup();st.innerHTML='<div class="gameHud" id="huntHudFixed">❤️ 0 / 7</div><div class="huntHint">المسي القلوب السبعة ❤️</div>';let score=0,ended=false,clockId;const hearts=new Set();const cleanup=()=>{ended=true;clearInterval(clockId);hearts.forEach(h=>h.remove());hearts.clear()};const popup=()=>{if(ended)return;ended=true;clearInterval(clockId);hearts.forEach(h=>h.remove());hearts.clear();const pop=document.createElement('div');pop.className='lovePopup show';pop.innerHTML='<div class="lovePopupBox"><div class="loveBig">❤️</div><div class="loveText">بحبك '+(names[world()]||'بيان')+'</div><div class="loveSub">جمعتِ كل القلوب ❤️</div><button class="btn loveClose" type="button">كملي ❤️</button></div>';document.body.appendChild(pop);pop.querySelector('.loveClose').onclick=()=>pop.remove();if(typeof window.rain==='function')window.rain(['❤️','💗','💖','💕'],50)};const update=()=>{const h=document.getElementById('huntHudFixed');if(h)h.textContent='❤️ '+score+' / 7'};const spawn=()=>{if(ended||score>=7)return;const h=document.createElement('button');h.type='button';h.className='tapHeart';h.textContent=['❤️','💗','💖'][Math.floor(Math.random()*3)];h.style.left=(6+Math.random()*84)+'%';h.style.top=(18+Math.random()*70)+'%';h.onclick=e=>{e.preventDefault();e.stopPropagation();if(ended)return;h.remove();hearts.delete(h);score++;update();if(score>=7)popup()};st.appendChild(h);hearts.add(h)};for(let i=0;i<4;i++)spawn();clockId=setInterval(()=>{if(!ended)while(hearts.size<4)spawn()},700);window.gameCleanup=cleanup};

  const style=document.createElement('style');style.textContent=`.dynamicTool{display:inline-block}.bouquetChoices{display:flex;flex-wrap:wrap;justify-content:center;gap:12px;margin:70px 12px 18px}.bouquetFlower{width:72px;height:72px;border-radius:20px;border:1px solid #fff3;background:#fff1;font-size:38px;cursor:pointer;transition:.25s}.bouquetFlower.selected{transform:translateY(-7px) scale(1.08);background:#ff9fbd33;box-shadow:0 0 25px #ff9fbd88;border-color:#ffd8e5}.bouquetPreview{min-height:52px;padding:12px;border-radius:18px;background:#fff1;border:1px solid #fff2}.letterLine{display:block;white-space:nowrap;text-align:right}.paper{overflow:visible!important;z-index:40!important;line-height:1.9!important}.envelope{overflow:visible!important}.envelope.open .paper{transform:translateY(-155px)!important;z-index:50!important}.envelope.open .flap{z-index:5!important}.lovePopup{position:fixed!important;inset:0!important;z-index:2147483000!important;display:grid!important;place-items:center!important}.lovePopup.show{opacity:1!important;pointer-events:auto!important}.lovePopupBox{position:relative!important;z-index:2147483001!important}@media(max-width:620px){.paper{padding:18px!important;font-size:17px!important}.letterLine{font-size:17px}.envelope.open .paper{transform:translateY(-155px)!important}}`;document.head.appendChild(style);
})();