(()=>{
const poemLines=[
'صَبَاحُ الخَيْرِ لِوَجْهِكِ الذِي أَقْبَلَ فَأَنَارَ ، وَلِعَيْنَيْكِ اللَّتَيْنِ تَخْتَصِرَانِ النَّهَارْ',
'أَشْرَقَتِ الشّمْسُ فَطَابَ الوُجُودُ وَاسْتَدَار، وأَقْبَلتِ فِي قَلْبِي فَتَوَهَجَ العِشْقُ وَ اسْتَنَارْ',
'يَبْدَأُ عُمْرِي حِينَمَا يَلُوحُ طَيْفُكِ المَجِيدْ ، وَيَسْتَقِيمُ نَبْضِي إِذْ يَزُورُنِي حُسْنُكِ الفَرِيدْ',
'فَمَا الصّبَاحُ فِي عُرْفِي إِلا لَمْحَةً مِنْ خَيَالِكِ ، وَمَا الضِّيَاءُ فِي كَوْنِي إِلا خُطْوَةً فِي دَلَالِكِ ... ❤️صَبَاحِي أَنْتِ❤️'
];
const css=`#poemCity.screen{background:radial-gradient(circle at 50% 15%,#fff7dc 0,#fbe7f0 42%,#211326 100%);overflow:auto;z-index:99999}.poemCard{max-width:900px!important;background:rgba(255,255,255,.86)!important;backdrop-filter:blur(10px);padding:24px!important}.poemBack{margin-bottom:18px}.poemIntro{text-align:center}.poemMap{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:22px 0}.poemGate{min-height:115px;border:1px solid rgba(130,45,90,.2);border-radius:24px;background:linear-gradient(145deg,#fff,#ffeef6);font-size:22px;color:#7d214f;box-shadow:0 8px 24px rgba(90,30,70,.1);cursor:pointer;transition:.3s}.poemGate:active{transform:scale(.96)}.poemGate.revealed{background:linear-gradient(145deg,#fff4cf,#ffddeb)}.poemLine{display:none;margin:12px 0;padding:18px 16px;border-radius:22px;background:rgba(255,255,255,.9);color:#682447;font-size:clamp(19px,4.7vw,29px);line-height:2;text-align:center;box-shadow:0 7px 20px rgba(80,20,60,.08);animation:poemIn .6s ease both}.poemLine.show{display:block}.poemFinal{font-weight:800;font-size:clamp(24px,6vw,38px);color:#b31f62}.poemHint{text-align:center;color:#8b5370;margin:8px}.poemDone{display:none;text-align:center;font-size:20px;color:#8b315e;margin-top:14px}.poemDone.show{display:block;animation:poemIn .6s ease both}@keyframes poemIn{from{opacity:0;transform:translateY(14px) scale(.98)}to{opacity:1;transform:none}}@media(max-width:600px){.poemMap{grid-template-columns:1fr}.poemCard{padding:18px!important}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
window.openPoemCity=()=>{let page=document.getElementById('poemCity');if(!page){page=document.createElement('section');page.id='poemCity';page.className='screen';page.innerHTML='<div class="card poemCard"><button class="backWorld poemBack" type="button">↩️ رجوع</button><div class="hero">🏙️✨</div><div class="poemIntro"><h2>مدينة الشعر</h2><p>كل باب في المدينة يخبي سطر من قصيدتك ❤️</p></div><div class="poemMap"></div><div class="poemHint">افتحي الأبواب بالترتيب... وشوفي القصيدة وهي تبنى قدامك ✨</div><div id="poemDone" class="poemDone">اكتملت المدينة ❤️🌹</div></div>';document.body.appendChild(page);page.querySelector('.poemBack').onclick=()=>page.classList.remove('active');const map=page.querySelector('.poemMap');poemLines.forEach((line,i)=>{const gate=document.createElement('button');gate.className='poemGate';gate.innerHTML=['🌅<br>بوابة الصباح','☀️<br>شارع النور','🌿<br>حديقة العمر','❤️<br>قصر النهاية'][i];const p=document.createElement('div');p.className='poemLine';p.textContent=line;gate.onclick=()=>{if(i>0&&!map.children[i-1].querySelector('.poemLine')?.classList.contains('show'))return;gate.classList.add('revealed');p.classList.add('show');if(i===poemLines.length-1){page.querySelector('#poemDone').classList.add('show');if(typeof rain==='function')rain(['🌹','🌸','❤️','✨'],35);}};const wrap=document.createElement('div');wrap.appendChild(gate);wrap.appendChild(p);map.appendChild(wrap);});}page.classList.add('active');window.scrollTo(0,0);};
const add=()=>{if(document.querySelector('.poemCityHome'))return;const host=document.querySelector('#start .choices');if(!host)return;const b=document.createElement('button');b.className='tile poemCityHome';b.innerHTML='<span>🏙️</span><b>مدينة الشعر</b><small>قصيدتك التفاعلية</small>';b.onclick=window.openPoemCity;host.appendChild(b)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();