(()=>{
const poemLines=[
'صَبَاحُ الخَيْرِ لِوَجْهِكِ الذِي أَقْبَلَ فَأَنَارَ ، وَلِعَيْنَيْكِ اللَّتَيْنِ تَخْتَصِرَانِ النَّهَارْ',
'أَشْرَقَتِ الشّمْسُ فَطَابَ الوُجُودُ وَاسْتَدَار، وأَقْبَلتِ فِي قَلْبِي فَتَوَهَجَ العِشْقُ وَ اسْتَنَارْ',
'يَبْدَأُ عُمْرِي حِينَمَا يَلُوحُ طَيْفُكِ المَجِيدْ ، وَيَسْتَقِيمُ نَبْضِي إِذْ يَزُورُنِي حُسْنُكِ الفَرِيدْ',
'فَمَا الصّبَاحُ فِي عُرْفِي إِلا لَمْحَةً مِنْ خَيَالِكِ ، وَمَا الضِّيَاءُ فِي كَوْنِي إِلا خُطْوَةً فِي دَلَالِكِ ... ❤️صَبَاحِي أَنْتِ❤️'
];
const css=`#poemCity.screen{background:radial-gradient(circle at 50% 15%,#fff7dc 0,#fbe7f0 42%,#211326 100%);overflow:auto;z-index:99999}.poemCard{max-width:900px!important;background:rgba(255,255,255,.9)!important;backdrop-filter:blur(10px);padding:24px!important}.poemBack{margin-bottom:18px}.poemIntro{text-align:center}.poemLine{display:block;margin:16px 0;padding:22px 18px;border-radius:22px;background:rgba(255,255,255,.94);color:#682447;font-size:clamp(20px,4.8vw,30px);line-height:2;text-align:center;box-shadow:0 7px 20px rgba(80,20,60,.08);animation:poemIn .6s ease both}.poemLine:nth-child(2){animation-delay:.12s}.poemLine:nth-child(3){animation-delay:.24s}.poemLine:nth-child(4){animation-delay:.36s}.poemFinal{font-weight:800;font-size:clamp(25px,6vw,39px);color:#b31f62}.poemBack{display:block;margin-bottom:18px}@keyframes poemIn{from{opacity:0;transform:translateY(14px) scale(.98)}to{opacity:1;transform:none}}@media(max-width:600px){.poemCard{padding:18px!important}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
window.openPoemCity=()=>{let page=document.getElementById('poemCity');if(!page){page=document.createElement('section');page.id='poemCity';page.className='screen';page.innerHTML='<div class="card poemCard"><button class="backWorld poemBack" type="button">↩️ رجوع</button><div class="hero">🏙️✨</div><div class="poemIntro"><h2>مدينة الشعر</h2><p>قصيدتك كاملة ❤️</p></div><div class="poemFull"></div></div>';document.body.appendChild(page);page.querySelector('.poemBack').onclick=()=>{page.classList.remove('active');document.getElementById('start')?.classList.add('active');window.scrollTo(0,0)};const box=page.querySelector('.poemFull');poemLines.forEach((line,i)=>{const p=document.createElement('div');p.className='poemLine'+(i===3?' poemFinal':'');p.textContent=line;box.appendChild(p);});}document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));page.classList.add('active');window.scrollTo(0,0);};
const add=()=>{if(document.querySelector('.poemCityHome'))return;const host=document.querySelector('#start .choices');if(!host)return;const b=document.createElement('button');b.className='tile poemCityHome';b.innerHTML='<span>🏙️</span><b>مدينة الشعر</b><small>قصيدتك كاملة</small>';b.onclick=window.openPoemCity;host.appendChild(b)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();