const A=document.getElementById('audio');let current='';let timer=null;
const songs={bayan:'رفيقة غيم.mp3',byoun:'انت الطريق.mp3',byonti:'اميرك جاء.mp3'};
const $=id=>document.getElementById(id);function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
function pick(name,id){current=id;A.src=encodeURI(songs[id]);A.loop=true;A.play().catch(()=>{});go(id);if(navigator.vibrate)navigator.vibrate(30);if(id==='bayan')bayanStart();if(id==='byoun')byounStart();if(id==='byonti')byontiStart()}
function home(){A.pause();A.currentTime=0;current='';go('start')}
function toggleAudio(){if(A.paused){A.play().catch(()=>{});$('music').textContent='🎵 شغال'}else{A.pause();$('music').textContent='🔇 إيقاف'}}
document.addEventListener('pointerdown',()=>{if(current&&A.paused)A.play().catch(()=>{})},{passive:true});
function msg(id,text){$(id).innerHTML=text;$(id).classList.add('show')}
function rain(chars=['❤️','💗','💖'],count=45){for(let i=0;i<count;i++){const e=document.createElement('span');e.className='heartDrop';e.textContent=chars[Math.floor(Math.random()*chars.length)];e.style.left=Math.random()*100+'vw';e.style.setProperty('--x',(Math.random()*160-80)+'px');e.style.animationDuration=(3+Math.random()*3)+'s';e.style.animationDelay=Math.random()*1.4+'s';document.body.appendChild(e);setTimeout(()=>e.remove(),7000)}}
function bayanStart(){rain(['🌹','🌸','❤️'],18);for(let i=0;i<5;i++){const b=document.createElement('span');b.className='butterfly';b.textContent='🦋';b.style.left=10+Math.random()*75+'%';b.style.top=20+Math.random()*55+'%';$('bayanStage').appendChild(b)}}
function flowerGame(){const st=$('bayanStage');st.innerHTML='<div class="flower" id="flower">🌱</div><div class="msg show" style="position:absolute;bottom:12px;left:12px;right:12px">اسقيها بالضغط عليها 3 مرات 🌱</div>';let n=0;$('flower').onclick=()=>{n++;$('flower').textContent=n===1?'🌿':n===2?'🌷':'🌹';if(n>=3){$('flower').classList.add('bloom');msg('bayanMsg','تفتحت الوردة... لأنها استنت لمسة منك 🌹❤️');rain(['🌸','❤️'],20)}}}
function huntHearts(){const st=$('bayanStage');st.innerHTML='<div class="msg show">صيد القلوب ❤️ اضغطي 7 قلوب قبل ما تختفي!</div>';let score=0;for(let i=0;i<7;i++){const h=document.createElement('button');h.className='petal';h.textContent='❤️';h.style.left=10+Math.random()*80+'%';h.style.top=45+Math.random()*40+'%';h.style.animationDuration=(2.2+Math.random()*1.5)+'s';h.onclick=()=>{if(h.disabled)return;h.disabled=true;h.remove();score++;msg('bayanMsg',`جمعتِ ${score}/7 ❤️`);if(score===7){msg('bayanMsg','فزتي! كل القلوب بالنهاية كانت رايحة لبيان ❤️🏆');rain(['❤️','💗','🌹'],35)}};st.appendChild(h)}}
function garden(){const st=$('bayanStage');st.innerHTML='<div class="msg show">فتشي بالحديقة واضغطي على النقاط المضيئة ✨</div>';const texts=['لقيتي وردة مخبية 🌹','فراشة بتقولك انك مميزة 🦋','قلب صغير كان مستنيك ❤️','مفاجأة: اليوم أحلى لأنك هون 💗'];texts.forEach((t,i)=>{const d=document.createElement('button');d.className='gardenDot';d.style.left=(10+Math.random()*78)+'%';d.style.top=(25+Math.random()*60)+'%';d.onclick=()=>{msg('bayanMsg',t);d.remove();rain(['🌸'],8)};st.appendChild(d)})}
function bayanStart(){const st=$('bayanStage');st.innerHTML='';rain(['🌹','🌸','❤️'],18);for(let i=0;i<4;i++){const b=document.createElement('span');b.className='butterfly';b.textContent='🦋';b.style.left=10+Math.random()*70+'%';b.style.top=15+Math.random()*65+'%';st.appendChild(b)}}
function constellation(){const st=$('byounStage');st.innerHTML='<div class="msg show">كوّني كوكبة من 5 نجوم ✨ اضغطي النجوم بالترتيب</div>';let n=0;for(let i=0;i<5;i++){const s=document.createElement('button');s.className='star';s.textContent='⭐';s.style.left=(10+Math.random()*78)+'%';s.style.top=(25+Math.random()*60)+'%';s.onclick=()=>{if(i!==n){msg('byounMsg','مش هاي النجمة 😌 جرّبي الثانية');return}n++;s.style.color='#fff1a8';msg('byounMsg',`${n}/5 نجوم`);if(n===5){msg('byounMsg','اكتملت الكوكبة... وسميتها بيون ⭐🌙');rain(['⭐','🌙'],30)}};st.appendChild(s)}}
function moon(){const st=$('byounStage');st.innerHTML='<div class="msg show">المسي القمر 5 مرات وشوفي شو بصير 🌙</div><div class="flower" id="moon">🌙</div>';let n=0;$('moon').onclick=()=>{n++;$('moon').textContent=n%2?'🌙':'🌕';if(n===5){msg('byounMsg','القمر اكتمل... بس لسه ما غطّى على حلاوة بيون 🌕❤️');rain(['🌙','⭐'],25)}}}
function starCatch(){const st=$('byounStage');st.innerHTML='<div class="msg show">نجوم ساقطة! اضغطي 8 قبل ما توصل تحت ⭐</div>';let score=0;for(let i=0;i<8;i++){const s=document.createElement('button');s.className='star';s.textContent='⭐';s.style.left=10+Math.random()*80+'%';s.style.top=15+Math.random()*65+'%';s.onclick=()=>{s.remove();score++;if(score===8){msg('byounMsg','جمعتِ السماء كلها ⭐🏆');rain(['⭐','💙'],35)}};st.appendChild(s)}}
function byounStart(){rain(['⭐','🌙','💙'],15);const st=$('byounStage');st.innerHTML='<div class="msg show">السماء الليلة إلها لعبة مخبية... اختاري واحدة من الفعاليات ✨</div>'}
const loveWords=['روحي','حياتي','عمري','قلبي','دنيتي','أغلى ما عندي','أحلى صدفة','راحة بالي'];function wordMachine(){let i=0;const out=$('word');clearInterval(timer);timer=setInterval(()=>{out.textContent=loveWords[i++%loveWords.length];if(i>12)clearInterval(timer)},100)}
function box(){const b=$('giftBox');b.classList.toggle('open');if(b.classList.contains('open')){msg('byontiMsg','المفاجأة: لو أعطيتك كل الكلام، برضه ما بكفي ❤️🎁');rain(['💗','💖','💕'],30)}}
function dragMemories(){const d=$('drag');let n=0;d.addEventListener('click',()=>{n++;d.scrollTo({left:d.scrollWidth,behavior:'smooth'});if(n>=3)msg('byontiMsg','كل ذكرى إلها مكان... وأحلى مكان إلها بقلبك ❤️')},{once:false})}
function heartBeat(){const st=$('byontiStage');st.innerHTML='<div class="msg show">اضغطي القلب مع النبض ❤️</div><div class="flower" id="beat">🤍</div>';let n=0;$('beat').onclick=()=>{n++;$('beat').textContent=n%2?'❤️':'💗';$('beat').style.transform=`translate(-50%,-50%) scale(${1+n*.06})`;if(n===8){msg('byontiMsg','هيك صار القلب يعرف إيقاعه ❤️');rain(['❤️','💗','💖'],40)}}}
function byontiStart(){rain(['❤️','💗','💖'],18);wordMachine()}
function openEnvelope(){go('bayanLetter');rain(['🌸','❤️'],15)}
window.flowerGame=flowerGame;window.huntHearts=huntHearts;window.garden=garden;window.constellation=constellation;window.moon=moon;window.starCatch=starCatch;window.wordMachine=wordMachine;window.box=box;window.heartBeat=heartBeat;window.openEnvelope=openEnvelope;