const A=document.getElementById('audio');
let current='';let timer=null;let rainTimer=null;let gameCleanup=null;
const songs={bayan:'رفيقة غيم.mp3',byoun:'انت الطريق.mp3',byonti:'اميرك جاء.mp3'};
const $=id=>document.getElementById(id);
const safe=(id)=>$(id);
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const el=$(id);if(el)el.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function playAudio(){if(!current)return;A.play().then(()=>{$('music').textContent='🎵 شغال'}).catch(()=>{});}
function pick(name,id){current=id;A.src=encodeURI(songs[id]);A.loop=true;A.load();playAudio();go(id);if(navigator.vibrate)navigator.vibrate(30);if(gameCleanup)gameCleanup();if(id==='bayan')bayanStart();if(id==='byoun')byounStart();if(id==='byonti')byontiStart();}
function home(){if(gameCleanup)gameCleanup();A.pause();A.currentTime=0;current='';go('start');}
function toggleAudio(){if(A.paused)playAudio();else{A.pause();$('music').textContent='🔇 إيقاف';}}
document.addEventListener('pointerdown',e=>{if(current&&A.paused)playAudio();const t=e.target;if(t&&t.closest&&t.closest('button,.tile,.choice,.game,.btn'))spark(e.clientX,e.clientY);},{passive:true});
function msg(id,text){const el=$(id);if(!el)return;el.innerHTML=text;el.classList.add('show');}
function rain(chars=['❤️','💗','💖'],count=32){for(let i=0;i<count;i++){const e=document.createElement('span');e.className='heartDrop';e.textContent=chars[Math.floor(Math.random()*chars.length)];e.style.left=Math.random()*100+'vw';e.style.setProperty('--x',(Math.random()*180-90)+'px');e.style.animationDuration=(3.8+Math.random()*3)+'s';e.style.animationDelay=(Math.random()*1.5)+'s';document.body.appendChild(e);setTimeout(()=>e.remove(),8000);}}
function spark(x,y){for(let i=0;i<5;i++){const e=document.createElement('span');e.className='spark';e.textContent=['✦','♡','✨'][i%3];e.style.left=x+'px';e.style.top=y+'px';e.style.setProperty('--x',(Math.random()*90-45)+'px');e.style.setProperty('--y',(Math.random()*90-55)+'px');document.body.appendChild(e);setTimeout(()=>e.remove(),950);}}
function addWorldTools(stageId,items){const host=$(stageId)?.parentElement?.querySelector('.tools');if(!host)return;items.forEach(([label,fn])=>{const b=document.createElement('button');b.className='tile';b.textContent=label;b.onclick=fn;host.appendChild(b);});}
function clearStage(st){if(gameCleanup){gameCleanup();gameCleanup=null;}st.innerHTML='';}
function bayanStart(){const st=$('bayanStage');clearStage(st);rain(['🌹','🌸','❤️'],18);for(let i=0;i<4;i++){const b=document.createElement('span');b.className='butterfly';b.textContent='🦋';b.style.left=10+Math.random()*72+'%';b.style.top=18+Math.random()*62+'%';st.appendChild(b);}addWorldTools('bayanStage',[["🌸 باقة سرية",bouquetGame],["🦋 طيري مع الفراشات",butterflyGame],["💌 رسالة مخفية",secretRose]]);}
function flowerGame(){const st=$('bayanStage');clearStage(st);st.innerHTML='<div class="msg show">اسقي الوردة 3 مرات ❤️ كل لمسة تقربها من التفتح</div><div class="flower" id="flower">🌱</div>';let n=0;const f=$('flower');f.onclick=()=>{n++;f.textContent=['🌱','🌿','🌷','🌹'][Math.min(n,3)];f.style.transform=`translate(-50%,-50%) scale(${1+n*.12})`;if(n>=3){f.classList.add('bloom');msg('bayanMsg','تفتحت الوردة... وكانت مستنية لمستك 🌹❤️');rain(['🌸','❤️'],22);}};}
function huntHearts(){const st=$('bayanStage');clearStage(st);st.innerHTML='<div class="msg show">❤️ صيد القلوب — اجمعي 7 قلوب قبل انتهاء الوقت</div><div class="gameHud" id="huntHud">7 قلوب · 20 ثانية</div>';let score=0,time=20,ended=false;const hearts=[];const hud=$('huntHud');function finish(win){if(ended)return;ended=true;hearts.forEach(h=>h.remove());clearInterval(clock);msg('bayanMsg',win?'فزتي! جمعتِ كل القلوب ❤️🏆':'خلص الوقت 😌 بس كل القلوب بالنهاية لبيان ❤️');if(win)rain(['❤️','💗','🌹'],35);}for(let i=0;i<7;i++){const h=document.createElement('button');h.className='tapHeart';h.textContent=['❤️','💗','💖'][i%3];h.style.left=(7+Math.random()*84)+'%';h.style.top=(25+Math.random()*62)+'%';h.style.animationDelay=(i*.08)+'s';h.onclick=()=>{if(ended)return;h.remove();score++;hud.textContent=`${7-score} قلوب · ${time} ثانية`;if(score===7)finish(true);};st.appendChild(h);hearts.push(h);}const clock=setInterval(()=>{time--;hud.textContent=`${7-score} قلوب · ${time} ثانية`;if(time<=0)finish(false);},1000);gameCleanup=()=>{clearInterval(clock);ended=true;};}
function garden(){const st=$('bayanStage');clearStage(st);st.innerHTML='<div class="msg show">فتشي بالحديقة واضغطي على 4 نقاط مضيئة ✨</div>';let found=0;const texts=['وردة مخبية إلك 🌹','فراشة تركتلك أمنية 🦋','قلب صغير كان مستنيك ❤️','آخر مفاجأة: وجودك لحاله كفاية 💗'];texts.forEach(t=>{const d=document.createElement('button');d.className='gardenDot';d.style.left=(8+Math.random()*82)+'%';d.style.top=(25+Math.random()*65)+'%';d.onclick=()=>{d.remove();found++;msg('bayanMsg',t);rain(['🌸'],6);if(found===4){msg('bayanMsg','لقيتي كل أسرار الحديقة 🌷👑');rain(['🌹','❤️'],18);}};st.appendChild(d);});}
function bouquetGame(){const st=$('bayanStage');clearStage(st);st.innerHTML='<div class="msg show">اختاري 3 ورود لتصنعي باقة بيان 🌷</div>';let n=0;['🌹','🌷','🌸','🌺','🌻'].forEach((x,i)=>{const b=document.createElement('button');b.className='tapHeart';b.textContent=x;b.style.left=(8+i*18)+'%';b.style.top=(42+(i%2)*18)+'%';b.onclick=()=>{b.disabled=true;b.style.transform='scale(1.3)';n++;if(n===3){msg('bayanMsg','باقة كاملة لبيان 🌷🌹🌸');rain(['🌸','🌹'],24);}};st.appendChild(b);});}
function butterflyGame(){const st=$('bayanStage');clearStage(st);st.innerHTML='<div class="msg show">اضغطي على 5 فراشات قبل ما تطير 🦋</div>';let n=0;for(let i=0;i<5;i++){const b=document.createElement('button');b.className='butterfly';b.textContent='🦋';b.style.left=5+Math.random()*82+'%';b.style.top=20+Math.random()*65+'%';b.onclick=()=>{b.remove();n++;if(n===5){msg('bayanMsg','مسكتيهم كلهم 🦋❤️');rain(['🦋','🌸'],20);}};st.appendChild(b);}}
function secretRose(){msg('bayanMsg','في وردة ما بتنشاف بالعين... هي الورد اللي زرعتيه بقلبي 🌹❤️');}
function constellation(){const st=$('byounStage');clearStage(st);st.innerHTML='<div class="msg show">كوّني كوكبة من 5 نجوم بالترتيب ✨</div>';let n=0;const stars=[];for(let i=0;i<5;i++){const s=document.createElement('button');s.className='star';s.textContent='⭐';s.style.left=8+Math.random()*82+'%';s.style.top=22+Math.random()*65+'%';s.onclick=()=>{if(i!==n){msg('byounMsg','هاي مش النجمة المطلوبة 😌');return;}n++;s.classList.add('found');if(n===5){msg('byounMsg','اكتملت كوكبة بيون ⭐🌙');rain(['⭐','🌙'],30);}else msg('byounMsg',`${n}/5 نجوم`);};st.appendChild(s);stars.push(s);}}
function moon(){const st=$('byounStage');clearStage(st);st.innerHTML='<div class="msg show">المسي القمر 5 مرات... كل لمسة بتغيره 🌙</div><div class="flower" id="moon">🌙</div>';let n=0;$('moon').onclick=()=>{n++;$('moon').textContent=['🌙','🌒','🌓','🌔','🌕'][Math.min(n,4)];if(n===5){msg('byounMsg','صار بدر... بس لسه بيون أحلى 🌕❤️');rain(['🌙','⭐'],25);}};}
function starCatch(){const st=$('byounStage');clearStage(st);st.innerHTML='<div class="msg show">⭐ اصطادي 8 نجوم قبل ما تختفي</div>';let score=0;const stars=[];const spawn=()=>{if(score>=8)return;const s=document.createElement('button');s.className='star fallingStar';s.textContent='⭐';s.style.left=8+Math.random()*82+'%';s.style.top='-5%';s.onclick=()=>{s.remove();score++;msg('byounMsg',`${score}/8 نجوم`);if(score===8){msg('byounMsg','جمعتِ السماء كلها ⭐🏆');rain(['⭐','💙'],35);}else spawn();};st.appendChild(s);stars.push(s);};for(let i=0;i<8;i++)spawn();gameCleanup=()=>stars.forEach(s=>s.remove());}
function byounStart(){const st=$('byounStage');clearStage(st);rain(['⭐','🌙','💙'],15);st.innerHTML='<div class="msg show">السماء الليلة إلها أسرار... اختاري فعالية ✨</div>';addWorldTools('byounStage',[["🌠 امنية على نجمة",wishStar],["🪐 دوران الكواكب",orbitGame],["🔭 منظار بيون",telescopeGame]]);}
function wishStar(){const st=$('byounStage');clearStage(st);st.innerHTML='<div class="msg show">اكتبي أمنية في بالك ثم اضغطي النجمة ✨</div><div class="flower" id="wish">⭐</div>';let done=false;$('wish').onclick=()=>{if(done)return;done=true;msg('byounMsg','خبيتي أمنيتك بالسماء... وإن شاء الله تصير حقيقة ⭐💙');rain(['⭐','💙'],20);};}
function orbitGame(){const st=$('byounStage');clearStage(st);st.innerHTML='<div class="msg show">حركي الكوكب بإصبعك وخليه يلف حول القمر 🪐</div><div class="orbitMoon">🌙</div><div class="planet" id="planet">🪐</div>';const p=$('planet');let a=0;const move=e=>{a+=e.movementX||1;p.style.transform=`translate(-50%,-50%) rotate(${a}deg) translateX(90px) rotate(${-a}deg)`;};st.addEventListener('pointermove',move);gameCleanup=()=>st.removeEventListener('pointermove',move);}
function telescopeGame(){const st=$('byounStage');clearStage(st);st.innerHTML='<div class="msg show">اضغطي العدسة واكتشفي شو مخبي بالسماء 🔭</div><div class="scope" id="scope">🔭</div>';let n=0;$('scope').onclick=()=>{n++;const t=['نجمة صغيرة بتحبك ⭐','قمر حافظ اسمك 🌙','أمنية قريبة منك ✨','رسالة من السماء: بيون غالية 💙'][Math.min(n-1,3)];msg('byounMsg',t);if(n===4)rain(['⭐','🌙'],18);};}
const loveWords=['روحي','حياتي','عمري','قلبي','دنيتي','أغلى ما عندي','أحلى صدفة','راحة بالي'];function wordMachine(){const out=$('word');if(!out)return;clearInterval(timer);let i=0;out.classList.add('wordSwap');timer=setInterval(()=>{out.textContent=loveWords[i++%loveWords.length];if(i>18)clearInterval(timer);},140);}
function box(){const b=$('giftBox');if(!b)return;b.classList.toggle('open');if(b.classList.contains('open')){msg('byontiMsg','المفاجأة الأولى 🎁: لو أعطيتك كل الكلام، برضه ما بكفي ❤️');rain(['💗','💖','💕'],30);}}
function heartBeat(){const st=$('byontiStage');clearStage(st);st.innerHTML='<div class="msg show">اضغطي القلب مع النبض ❤️</div><div class="flower" id="beat">🤍</div>';let n=0;$('beat').onclick=()=>{n++;$('beat').textContent=n%2?'❤️':'💗';$('beat').style.transform=`translate(-50%,-50%) scale(${1+Math.min(n,12)*.05})`;if(n===8){msg('byontiMsg','هيك صار القلب يعرف إيقاعه ❤️');rain(['❤️','💗','💖'],40);}};}
function byontiStart(){const st=$('byontiStage');clearStage(st);rain(['❤️','💗','💖'],18);wordMachine();addWorldTools('byontiStage',[["🧩 فكّي لغز الحب",lovePuzzle],["🎀 اختاري شريط الذكرى",ribbonGame],["💫 لمسة سحرية",magicTouch]]);}
function lovePuzzle(){const st=$('byontiStage');clearStage(st);st.innerHTML='<div class="msg show">اختاري القطعة التي تكمل القلب 💗</div>';const opts=['❤️','💔','💙','🌙'];opts.forEach((x,i)=>{const b=document.createElement('button');b.className='tapHeart';b.textContent=x;b.style.left=(12+i*23)+'%';b.style.top='48%';b.onclick=()=>{if(x==='❤️'){msg('byontiMsg','صح! القطعة الناقصة كانت الحب نفسه ❤️🏆');rain(['❤️','💗'],25);}else msg('byontiMsg','قريبة... جربي قطعة ثانية 😌');};st.appendChild(b);});}
function ribbonGame(){const st=$('byontiStage');clearStage(st);st.innerHTML='<div class="msg show">اختاري الشريط اللي بدك تفتحيه 🎀</div>';['🎀','🎁','💌'].forEach((x,i)=>{const b=document.createElement('button');b.className='tapHeart';b.textContent=x;b.style.left=(18+i*28)+'%';b.style.top='45%';b.onclick=()=>{const t=['ذكرى: أول مرة صار اسمك قريب من قلبي ❤️','هدية: يومك أحلى من أي هدية 🎁','رسالة: انتي أجمل تفصيل بحياتي 💌'][i];msg('byontiMsg',t);rain(['💗'],10);};st.appendChild(b);});}
function magicTouch(){const st=$('byontiStage');clearStage(st);st.innerHTML='<div class="msg show">المسي الشاشة 6 مرات وشوفي السحر ✨</div><div class="magicHeart">💗</div>';let n=0;const click=()=>{n++;st.style.setProperty('--magic',n);rain(['✨','💗'],2);if(n>=6){msg('byontiMsg','السحر الحقيقي؟ إنك وصلتي لهون ❤️✨');st.removeEventListener('pointerdown',click);rain(['❤️','💖','✨'],35);}};st.addEventListener('pointerdown',click);gameCleanup=()=>st.removeEventListener('pointerdown',click);}
function openEnvelope(){go('bayanLetter');rain(['🌸','❤️'],15);}
window.flowerGame=flowerGame;window.huntHearts=huntHearts;window.garden=garden;window.constellation=constellation;window.moon=moon;window.starCatch=starCatch;window.wordMachine=wordMachine;window.box=box;window.heartBeat=heartBeat;window.openEnvelope=openEnvelope;window.bouquetGame=bouquetGame;window.butterflyGame=butterflyGame;window.secretRose=secretRose;window.wishStar=wishStar;window.orbitGame=orbitGame;window.telescopeGame=telescopeGame;window.lovePuzzle=lovePuzzle;window.ribbonGame=ribbonGame;window.magicTouch=magicTouch;
